image: proboci/ubuntu-14.04-lamp:php7.0-nightly
assets:     
  - d8testsite.sql.gz
steps:
  - name: Update composer
    command: '/usr/local/bin/composer self-update'
  - name: Install drush-master for d8
    command: 'composer global require drush/drush:8.* ; cd /usr/local/bin ; mv drush drush7 ; ln -s $HOME/.composer/vendor/bin/drush drush'
  - name: Add Drupal package repository for Drupal 8.
    command: 'composer config -d /src/ repositories.drupal composer https://packages.drupal.org/8'
  - name: Install composer packages with dependencies.
    command: 'composer install -d /src/'
  - name: Probo site setup
    plugin: Drupal
    drupalVersion: 8
    database: d8testsite.sql.gz
    subDirectory: docroot
    databaseGzipped: true
    databaseUpdates: false
    revertFeatures: false
    clearCaches: true
