assets:     
  - d8testsite.sql.gz
steps:
  - name: Update Composer
    command: '/usr/local/bin/composer global update'
  - name: Install drush-master for d8
    command: 'composer global require drush/drush:8.* ; cd /usr/local/bin ; mv drush drush7 ; ln -s $HOME/.composer/vendor/bin/drush drush'
  - name: Probo site setup
    plugin: Drupal
    database: d8testsite.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    revertFeatures: false
    clearCaches: true
